hf_model_id: "mistralai/Mistral-7B-v0.3"
hf_data_parquet_url: "https://huggingface.co/datasets/Locutusque/function-calling-chatml/resolve/main/data/train-00000-of-00001-f0b56c6983b4a78f.parquet"
test_split: 0.05
